config/routes.rb
Rails.application.routes.draw do

  root 'painel/dashboard#index'

  devise_for :users, :path => '', :path_names => {:sign_in => 'login', :sign_out => 'logout'}, :only => [ :sessions ]

  namespace :painel do

    root 'dashboard#index'

    resources :users do
      member do
        patch :updatepassword
      end
    end

    resources :clients

    resources :products do
      collection do
        resources :categories, :except => [ :show, :new ]
      end
    end

    resources :sales, :except => [ :show, :update ] do
      collection do
        resources :payments
      end
    end 

  end

end

app/models/category.rb
class Category < ActiveRecord::Base

  validates :name, presence: true, uniqueness: true

  has_many :product
  
end

app/controllers/painel/base_controller.rb
class Painel::BaseController < ApplicationController
  
  before_action :authenticate_user!, :funcionario?, :ativo?

  layout 'painel'

  private

    def ativo?
      unless current_user.status != false
        sign_out @user
        redirect_to previous_url(current_user)
      end
    end

    def funcionario?
      if current_user.level != 'user'
        return true
      else
        sign_out @user
        redirect_to previous_url(current_user)
      end 
    end

    def previous_url(resource)
      session[:previous_url] || painel_root_path
    end

end

app/controllers/painel/categories_controller.rb
class Painel::CategoriesController < Painel::BaseController

  before_action :set_category, :only => [ :edit, :update, :destroy ]

  def index
    @category = Category.new
    @categories = Category.all
  end

  def create
    @category = Category.new(category_params)
    respond_to do |f|
      if @category.save
        f.html { redirect_to painel_categories_path }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |f|
      if @category.update_attributes(category_params)
        f.html { redirect_to painel_categories_path }
      end
    end
  end

  def destroy
    @category.destroy
    respond_to do |f|
      f.html { redirect_to painel_categories_path }
    end
  end

  private

    def category_params
      params.require(:category).permit(:name)
    end

    def set_category
      @category = Category.find(params[:id])
    end

end

app/controllers/painel/clients_controller.rb
class Painel::ClientsController < Painel::BaseController

  before_action :set_client, :only => [ :show, :edit, :update, :destroy ]

  def index
    @clients = Client.all
  end

  def new
    @client = Client.new
  end




  def create
    @client = Client.new(client_params)
    respond_to do |f|
      if @client.save
        f.json { render json: @client }
        f.html { redirect_to painel_clients_path }
      end
    end
  end

  def show

  end

  def edit

  end

  def update
    respond_to do |f|
      if @client.update_attributes(client_params)
        f.html { redirect_to painel_clients_path }
      end
    end
  end

  def destroy
    @client.destroy
    respond_to do |f|
      f.html { redirect_to painel_clients_path }
    end
  end

  private

    def client_params
      params.require(:client).permit(:name, :telephone, :cellphone, :email, :password, :password_confirmation, :CEP, :address_line, :number, :district, :city, :state, :status)
    end

    def set_client
      @client = Client.find(params[:id])
    end

end

app/controllers/painel/dashboard_controller.rb
class Painel::DashboardController < Painel::BaseController

  def index
    @client = Client.new
    @product = Product.new
    @clients = Client.order('id DESC').limit(10)
    @sale = Sale.new
    @sales = Sale.order('id DESC').take(10)
    @salesweek = Sale.sale_last_week
    @salestoday = Sale.sale_today
  end

end

app/controllers/painel/payments_controller.rb
class Painel::PaymentsController < Painel::BaseController

  before_action :set_payment, :only => [ :destroy ]

  def index
    @payments = Payment.all
    @payment  = Payment.new
  end

  def create
    @payment = Payment.new(payment_params)
    respond_to do |f|
      if @payment.save
        f.html { redirect_to painel_payments_path }
      end
    end
  end

  def destroy
    @payment.destroy
    respond_to do |f|
      if @payment.save
        f.html { redirect_to painel_payments_path }
      end
    end
  end

  private

    def payment_params
      params.require(:payment).permit(:name)
    end

    def set_payment
      @payment = Payment.find(params[:id])
    end

end

app/controllers/painel/products_controller.rb
class Painel::ProductsController < Painel::BaseController

  def index
    @products = Product.where("quantify > 0")
  end

  def new
    @product = Product.new
  end

  def show
    @product = Product.find(params[:id])
  end

  def create
    @product = Product.new(product_params)
    respond_to do |f|
      if @product.save
        f.json { render json: @product }
        f.html { redirect_to painel_products_path }
      end
    end
  end

  private

    def product_params
      params.require(:product).permit(:sku, :name, :price, :quantify, :category_id)
    end

end

app/controllers/painel/sales_controller.rb
class Painel::SalesController < Painel::BaseController

  def index
    @sales = Sale.all
  end

  def new
    @sale = Sale.new
    @sale.order_product.build
  end

  def create
    @sale = Sale.new(sale_params)
    @sale.employee_id = current_user.id
    respond_to do |f|
      if @sale.save
        f.json { render json: @sale }
        f.html { redirect_to painel_sales_path }
      end
    end
  end

  def destroy
    @sale.destroy
    respond_to do |f|
      f.html { redirect_to painel_sales_path }
    end
  end

  private

    def sale_params
      params.require(:sale).permit(:payment_id, :client_id, :price, product_ids: [])
    end

    def set_sale
      @sale = Sale.find(params[:id])
    end

end

app/controllers/painel/users_controller.rb
class Painel::UsersController < Painel::BaseController

  before_action :set_users, :only => [ :update, :show, :updatepassword ]
  # before_filter :validate_user, :only => :show

  def index
    @users = User.where(:level => 0)
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params_create)
    respond_to do |format|
      if @user.save
        format.json { render json: @user }
        format.html { redirect_to painel_users_path }
      end
    end
  end

  def show

  end

  def updatepassword
    respond_to do |f|
      if @user.update_attributes(user_params_update_password)
        f.html { redirect_to painel_user_path }
      end
    end
  end

  def update
    respond_to do |format|
      if @user.update_attributes(user_params_update)
        format.html { redirect_to painel_user_path }
      end
    end
  end

  private

    def validate_user
      redirect_to :controller => 'users', :action => 'show', :id => current_user unless current_user.id.to_s == params[:id]
    end

    def user_params_update
      params.require(:user).permit(:name, :birthday, :telephone, :cellphone, :email, :CEP, :address_line, :number, :district, :city, :state, :status)
    end

    def user_params_update_password
      params.require(:user).permit(:password, :password_confirmation, :current_password)
    end

    def user_params_create
      params.require(:user).permit(:name, :cpf, :birthday, :telephone, :cellphone, :email, :password, :password_confirmation, :CEP, :address_line, :number, :district, :city, :state, :status)
    end

    def set_users
      @user = User.find(params[:id])
    end

end

app/views/painel/categories/edit.html.erb
 <!-- Start Page Header -->
  <div class="page-header">
    <h1 class="title">Adicionar nova categoria de produto</h1>
    <ol class="breadcrumb">
      <li class="active">This is a quick overview of some features</li>
    </ol>

  </div>

  <div class="container-default">

    <div class="row">

      <div class="col-md-4">
        <%= form_for @category, :url => { :action => 'update' }, :html => { :class => 'form-horizontal' } do |f| %>
          <div class="form-group">
            <div class="col-sm-12">
              <%= f.label :name, "Nome da categoria" , class: "control-label form-label" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <%= f.submit 'Salvar', :class => 'btn btn-default right' %>
            </div>
          </div>
        <% end %>
      </div>

    </div>

  </div>

app/views/painel/categories/index.html.erb
  <!-- Start Page Header -->
  <div class="page-header">
    <h1 class="title">Adicionar nova categoria de produto</h1>
    <ol class="breadcrumb">
      <li class="active">This is a quick overview of some features</li>
    </ol>

  </div>

  <div class="container-default">

    <div class="row">

      <div class="col-md-4">
        <%= form_for @category, :url => { :action => 'create' }, :html => { :class => 'form-horizontal' } do |f| %>
          <div class="form-group">
            <div class="col-sm-12">
              <%= f.label :name, "Nome da categoria" , class: "control-label form-label" %>
              <%= f.text_field :name, class: "form-control" %>
            </div>
          </div>
          <div class="form-group">
            <div class="col-sm-12">
              <%= f.submit 'Salvar', :class => 'btn btn-default right' %>
            </div>
          </div>
        <% end %>
      </div>

      <div class="col-md-8">

        <table class="table table-bordered table-striped">
          <thead>
            <tr>
              <td>Nome</td>
              <td>Quantidade</td>
              <td>Ações</td>
            </tr>
          </thead>
          <tbody>
            <% @categories.each do |c| %>
            <tr>
              <td><%= c.name %></td>
              <td><%= c.product.count %></td>
              <td>
              <%= link_to edit_painel_category_path(c) do %>
                <i class="fa fa-pencil"></i>
              <% end %>
              <%= link_to painel_category_path(c), method: :delete, data: { confirm: "Você tem certeza?" } do %>
                <i class="fa fa-close"></i>
              <% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>

      </div>

    </div>

  </div>